## k-nearest neighbors (KNN) algorithm is a simple, easy-to-implement supervised machine learning algorithm that can be used to solve both classification and regression problems
#### A classification problem has a discrete value as its output. For example, "Person interested in insurance(1) or not(0)"  based on his age are discrete. There is no middle value between 0 and 1.
#### KNN algorithm assumes that similar things exist in close proximity. In other words, similar things are near to each other.

##### The KNN Algorithm
    1.  Load the data
    2.  Initialize K to your chosen number of neighbors
    3.  For each example in the data
    4.  Calculate the distance between each data point from our feature parameter.
    5.  Add the distance and the index of the example to an ordered collection
    6.  Sort the ordered collection of distances and indices from smallest to largest (in ascending order) by the distances
    7.  Pick the first K entries from the sorted collection
    8.  Get the labels of the selected K entries
    9.  If regression, return the mean of the K labels
    10. If classification, return the mode of the K labels

In [47]:
# Importing essential libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statistics

In [48]:
# Reading data into dataframe using pandas read_csv method
# Load the data
df=pd.read_csv("insurance.csv")
df

    Age  Insurance Interest
0    43                   1
1    29                   0
2    23                   0
3    49                   1
4    50                   1
5    35                   0
6    67                   1
7    89                   1
8    19                   0
9    27                   0
10   18                   0
11   46                   1
12   32                   1
13   48                   1
14   36                   0
15   32                   0
16   73                   1
17   28                   0
18   20                   0
19   62                   0

In [49]:
# Getting values from dataframe
data=df.values

# Initialize K to your chosen number of neighbors
k=3

In [50]:
# Implementing KNN algorithm

def KNN(data,age,k):
    
    # If not enough nearest neighbour's then return info that relates..    
    if(k>len(data)):
        return f"K({k}) should not be greater than count of total samples({len(data)})"
    
    # Initilizing array of tuples that holds our data
    DistanceIndexes=[]
    
    # For each sample in a given dataset, calculate distance and remember index of sample..
    for index,sample in enumerate(data):
        
        # Recording distance and it's respective index into an array
        DistanceIndexes.append((abs(sample[0]-age),index))
    
    # Sort recorded array and slice it down to k nearest neighbour's
    # get label's of indexes in sliced array
    # Because it is a classification problem, use mode instead od mean
    return statistics.mode([data[index][-1] for distance,index in sorted(DistanceIndexes)[:k]])

In [51]:
# Here is our prediction whether a person having age 62 can take insurance or not based on given dataset
KNN(data,62,6)

1